# Generated by Django 4.1.5 on 2023-02-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="complete",
            new_name="is_complete",
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("high", "HIGH"), ("medium", "MEDIUM"), ("low", "LOW")],
                default="low",
                max_length=50,
            ),
        ),
    ]
